[project]
name = 'decentralized-health-coverage-pool'
description = 'A peer-pooled micro-health coverage system built on Stacks blockchain'
authors = ['ozzydaniels78@gmail.com']
telemetry = true
cache_dir = './.clarinet'
requirements = []
boot_contracts = []

[contracts.health-pool]
path = 'contracts/Decentralized-Health-Coverage-Pool.clar'
clarity_version = 3
epoch = "3.0"

[contracts.referral-system]
path = 'contracts/referral-system.clar'
clarity_version = 3
epoch = "3.0"

[repl]
parser_version = 2

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
